spring.application.name=jbpharma

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/jbpharmapisip
spring.datasource.username=postgres
<<<<<<< Updated upstream
spring.datasource.password=root
=======
spring.datasource.password=0494trmd
spring.datasource.driver-class-name=org.postgresql.Driver
>>>>>>> Stashed changes

spring.jpa.show-sql=true